// ACHAAR KRARA — Product Data
// Do NOT edit this file by hand. Open admin.html, make your changes there,
// and click "Publish" or "Download" to generate a new version of this file.

const PRODUCTS = [
  {
    "name": "Mango Achaar",
    "desc": "Raw mango, mustard oil, fennel and a slow-roasted spice mix.",
    "heat": 2,
    "color": "#6B7A3A",
    "flavorProfile": { "tangy": 85, "spicy": 65, "salty": 75, "sweet": 20 },
    "images": [],
    "inStock": true,
    "sizes": {
      "500g": 260,
      "1kg": 480
    },
    "reviews": []
  },
  {
    "name": "Red Chili Achaar",
    "desc": "Whole red chilies, mustard seed and a sharp, tangy oil base.",
    "heat": 3,
    "color": "#A63A2E",
    "flavorProfile": { "tangy": 60, "spicy": 95, "salty": 80, "sweet": 10 },
    "images": [],
    "inStock": true,
    "sizes": {
      "500g": 280,
      "1kg": 520
    },
    "reviews": []
  },
  {
    "name": "Lime Achaar",
    "desc": "Slow sun-cured lime in a light, salty-sour masala.",
    "heat": 1,
    "color": "#D9A02B",
    "flavorProfile": { "tangy": 95, "spicy": 40, "salty": 85, "sweet": 15 },
    "images": [],
    "inStock": true,
    "sizes": {
      "400g": 200,
      "500g": 240,
      "1kg": 440
    },
    "reviews": []
  },
  {
    "name": "Mixed Veg Achaar",
    "desc": "Carrot, cauliflower and turnip, pickled together in mustard oil.",
    "heat": 1,
    "color": "#6B7A3A",
    "flavorProfile": { "tangy": 65, "spicy": 50, "salty": 70, "sweet": 30 },
    "images": [],
    "inStock": true,
    "sizes": {
      "400g": 210,
      "500g": 250,
      "1kg": 460
    },
    "reviews": []
  },
  {
    "name": "Green Chilli Achaar",
    "desc": "Bold, tangy green chilli pickle handcrafted in Himachal Pradesh with traditional spices, mustard oil, and authentic homemade flavours in every bite.",
    "heat": 3,
    "color": "#6B7A3A",
    "flavorProfile": { "tangy": 70, "spicy": 90, "salty": 75, "sweet": 10 },
    "images": [],
    "inStock": true,
    "sizes": {
      "500g": 250,
      "1kg": 500
    },
    "reviews": []
  },
  {
    "name": "Dheu Achaar",
    "desc": "Authentic Dheu (Monkey Fruit) pickle handcrafted in Himachal Pradesh with traditional spices and mustard oil, delivering a bold homemade tangy flavour.",
    "heat": 1,
    "color": "#6B7A3A",
    "flavorProfile": { "tangy": 85, "spicy": 50, "salty": 70, "sweet": 20 },
    "images": [],
    "inStock": true,
    "sizes": {
      "500g": 250,
      "1kg": 500
    },
    "reviews": []
  },
  {
    "name": "Nimbu khatha Meetha Achaar",
    "desc": "Sweet and tangy lemon pickle handcrafted in Himachal Pradesh with traditional spices, delivering a perfectly balanced homemade flavour in every bite.",
    "heat": 0,
    "color": "#6B7A3A",
    "flavorProfile": { "tangy": 90, "spicy": 25, "salty": 55, "sweet": 85 },
    "images": [],
    "inStock": true,
    "sizes": {
      "500g": 250,
      "1kg": 500
    },
    "reviews": []
  },
  {
    "name": "Lasuda Achaar",
    "desc": "",
    "heat": 0,
    "color": "#6B7A3A",
    "flavorProfile": { "tangy": 65, "spicy": 45, "salty": 65, "sweet": 25 },
    "images": [],
    "inStock": true,
    "sizes": {
      "500g": 250,
      "1kg": 500
    },
    "reviews": []
  }
];

const SETTINGS = {
  "whatsappNumber": "919015197375"
};
