// ACHAAR KRARA — Product Data
// Do NOT edit this file by hand. Open admin.html, make your changes there,
// and click "Publish" or "Download" to generate a new version of this file.

const PRODUCTS = [
  {
    "name": "Mango Achaar",
    "desc": "Raw mango, mustard oil, fennel and a slow-roasted spice mix.",
    "heat": 2,
    "color": "#6B7A3A",
    "images": [],
    "inStock": true,
    "sizes": {
      "400g": 220,
      "500g": 260,
      "1kg": 480
    },
    "reviews": []
  },
  {
    "name": "Red Chili Achaar",
    "desc": "Whole red chilies, mustard seed and a sharp, tangy oil base.",
    "heat": 3,
    "color": "#A63A2E",
    "images": [],
    "inStock": true,
    "sizes": {
      "400g": 240,
      "500g": 280,
      "1kg": 520
    },
    "reviews": []
  },
  {
    "name": "Lime Achaar",
    "desc": "Slow sun-cured lime in a light, salty-sour masala.",
    "heat": 1,
    "color": "#D9A02B",
    "images": [],
    "inStock": true,
    "sizes": {
      "400g": 200,
      "500g": 240,
      "1kg": 440
    },
    "reviews": []
  },
  {
    "name": "Mixed Veg Achaar",
    "desc": "Carrot, cauliflower and turnip, pickled together in mustard oil.",
    "heat": 1,
    "color": "#6B7A3A",
    "images": [],
    "inStock": true,
    "sizes": {
      "400g": 210,
      "500g": 250,
      "1kg": 460
    },
    "reviews": []
  }
];

const SETTINGS = {
  "whatsappNumber": "919015197375"
};
